// This file will define the context for your tRPC procedures, such as database access using Prisma.
// Your context holds data that all of your tRPC procedures will have access to, and is a 
// great place to put things like database connections or authentication information.

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// this function creates a ctx object which is passed into every tRPC procedure
// it will have ctx.prisma (prisma client instance)  and other services that is written in return statement
export const createContext = () => {
    return { prisma }; // Add Prisma Client to the context
};

// gives you the type of the object returned by the createContext function, which in this case is { prisma: PrismaClient }.
// prismaclient is a typescript class generated by prisma that has methods for the db models, db connection management
export type Context = Awaited<ReturnType<typeof createContext>>