export const data = [
    { id: 1, name: 'Alice', age: 25, job: 'Engineer', city: 'New York' },
    { id: 2, name: 'Bob', age: 30, job: 'Designer', city: 'Chicago' },
    { id: 3, name: 'Charlie', age: 35, job: 'Manager', city: 'Los Angeles' },
    { id: 4, name: 'David', age: 22, job: 'Developer', city: 'Houston' },
    { id: 5, name: 'Eve', age: 28, job: 'Analyst', city: 'Phoenix' },
    { id: 6, name: 'Frank', age: 40, job: 'Architect', city: 'Philadelphia' },
    { id: 7, name: 'Grace', age: 27, job: 'Product Owner', city: 'San Antonio' },
    { id: 8, name: 'Hank', age: 32, job: 'Scrum Master', city: 'San Diego' },
    { id: 9, name: 'Ivy', age: 24, job: 'QA Tester', city: 'Dallas' },
    { id: 10, name: 'Jack', age: 36, job: 'DevOps Engineer', city: 'San Jose' },
    { id: 11, name: 'Kate', age: 29, job: 'Data Scientist', city: 'Austin' },
    { id: 12, name: 'Leo', age: 33, job: 'Consultant', city: 'Jacksonville' },
    { id: 13, name: 'Mia', age: 31, job: 'HR Specialist', city: 'Fort Worth' },
    { id: 14, name: 'Nina', age: 26, job: 'Marketing Manager', city: 'Columbus' },
    { id: 15, name: 'Oscar', age: 38, job: 'Sales Director', city: 'Charlotte' },
    { id: 16, name: 'Paul', age: 34, job: 'Accountant', city: 'San Francisco' },
    { id: 17, name: 'Quinn', age: 23, job: 'Intern', city: 'Indianapolis' },
    { id: 18, name: 'Rachel', age: 39, job: 'CEO', city: 'Seattle' },
    { id: 19, name: 'Sam', age: 37, job: 'CTO', city: 'Denver' },
    { id: 20, name: 'Tina', age: 21, job: 'Student', city: 'Washington' },
];